/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAToken } from "./MockAToken";
export type { MockERC20 } from "./MockERC20";
export type { MockPool } from "./MockPool";
