name: Publish Docs (single-file app)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/publish-docs.yml'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend (single-file)
        working-directory: frontend
        run: npm run build

      - name: Publish to docs folder
        run: |
          mkdir -p docs
          cp frontend/dist/index.html docs/index.html

      - name: Commit and push docs update
        run: |
          if ! git diff --quiet -- docs/index.html; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/index.html
            git commit -m "docs: auto-publish single-file app [skip ci]"
            git push
          fi


