/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IPool } from "./IPool";
export type { IPoolAddressesProvider } from "./IPoolAddressesProvider";
export type { IProtocolDataProvider } from "./IProtocolDataProvider";
